--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.791.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 14/05/2022 15:25:54
-- Server version: 5.7.37
-- Client version: 4.1
--


SET NAMES 'utf8';








INSERT INTO webcup2022.migrations(id, migration, batch) VALUES
(1, '2014_10_12_000000_create_users_table', 1),
(2, '2014_10_12_100000_create_password_resets_table', 1),
(3, '2019_08_19_000000_create_failed_jobs_table', 1),
(4, '2019_12_14_000001_create_personal_access_tokens_table', 1),
(5, '2022_05_14_114825_create_duree_table', 1),
(6, '2022_05_14_114837_create_emplacement_table', 1),
(7, '2022_05_14_114852_create_type_capsule_table', 1),
(8, '2022_05_14_114914_create_capsule_table', 1),
(9, '2022_05_14_114936_create_facture_table', 1),
(10, '2022_05_14_114947_create_type_donnee_table', 1),
(11, '2022_05_14_115004_create_detail_facture_table', 1),
(12, '2022_05_14_115018_create_capsule_data_table', 1);




